# Generated by Django 4.0.4 on 2022-08-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('fecha_Vto', models.DateField()),
                ('precio', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos')),
            ],
        ),
    ]
